name: Weekly Report

on:
  workflow_dispatch:
  schedule:
    # 毎週金曜日
    # 16:00 JST = 7:00 UTC
    - cron: '0 7 * * 5'

jobs:
  run-weekly-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --frozen --no-dev

      - name: Run weekly report
        env:
          DISCORD_URL_WEEKLY_REPORT: ${{ secrets.DISCORD_URL_WEEKLY_REPORT }}
          KABU_PRICES_JSON_BASE64:  ${{ secrets.KABU_PRICES_JSON_BASE64 }}
        run: |
          uv run ./.src/discord_kabu_weekly_report.py

